gateway_url = "http://localhost:8000"
nef_url = "http://localhost:8888"
nef_gateway_url = "http://host.docker.internal:8000"

[sms_otp]
sms_backend = "mock"
otp_backend = "redis"
smsc_url = "http://localhost:7090"
sender_id = "1234"

[qos_profiles]
backend = "nef"

[location]
backend = "nef"

[qod_provisioning]
qod_provisioning_backend = "nef"
af_id = "gateway"

[nef]
auth = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDc0NzIxMjEsInN1YiI6IjEifQ.m9vZGpaP7V49WcpbqAuVtxS4a68MVjseJK_4yc2SQ6g"

[geofencing]
monitoring_url = "http://localhost:8888/nef/api/v1/3gpp-monitoring-event/v1/camara"
analytics_url = "http://localhost:8888/nef/api/v1/3gpp-analyticsexposure/v1/camara"
nef_webhook = "http://host.docker.internal:8000/geofencing/webhook"
geofencing_url = "http://localhost:8000/geofencing-subscriptions/v0"
