gateway_public_url = "http://localhost:8000"

[nef]
url = "http://localhost:8888"
base_path = "/nef/api/v1/"

gateway_af_id = "camara"
gateway_notification_url = "http://host.docker.internal:8000"

username = "admin@my-email.com"
password = "pass"


[sms_otp]
sms_backend = "mock"
otp_backend = "redis"
smsc_url = "http://localhost:7090"
sender_id = "1234"


[qos_profiles]
backend = "nef"


[location]
backend = "nef"


[qod_provisioning]
backend = "nef"

[qod]
backend = "nef"

[geofencing]
backend = "nef"


[reachability_status]
backend = "nef"

[roaming_status]
backend = "nef"
