gateway_url = "http://host.docker.internal:8000"
nef_url = "http://localhost:8888"

[sms_otp]
sms_backend = "mock"
otp_backend = "redis"
smsc_url = "http://localhost:7090"
sender_id = "1234"

[qos_profiles]
backend = "nef"

[location]
backend = "nef"

[qod_provisioning]
qod_provisioning_backend = "nef"
af_id = "gateway"
