# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# imagePullSecrets: []
imagePullSecrets:
  - name: regcred

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

mnc: 003
mcc: 999
mnoDomain: ims.mnc003.mcc999.3gppnetwork.org

database:
  name: ""
  storage:
    size: 1G
    storageClassName: local-path

pyhss:
  replicaCount: 1

  image:
    repository: atnog-harbor.av.it.pt/gsma-open-gw-apis/pyhss
    pullPolicy: Always # IfNotPresent
    tag: "latest"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

scscf:
  replicaCount: 1

  image:
    repository: atnog-harbor.av.it.pt/gsma-open-gw-apis/scscf
    pullPolicy: Always # IfNotPresent
    tag: "latest"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

icscf:
  replicaCount: 1

  image:
    repository: atnog-harbor.av.it.pt/gsma-open-gw-apis/icscf
    pullPolicy: Always # IfNotPresent
    tag: "latest"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

pcscf:
  replicaCount: 1

  publicNodePort: 5060

  image:
    repository: atnog-harbor.av.it.pt/gsma-open-gw-apis/pcscf
    pullPolicy: Always # IfNotPresent
    tag: "latest"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    privileged: true
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

smsc:
  replicaCount: 1

  image:
    repository: atnog-harbor.av.it.pt/gsma-open-gw-apis/smsc
    pullPolicy: Always # IfNotPresent
    tag: "latest"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

rtpengine:
  replicaCount: 1

  ports:
    min: 49000
    max: 50000

  image:
    repository: atnog-harbor.av.it.pt/gsma-open-gw-apis/rtpengine
    pullPolicy: Always # IfNotPresent
    tag: "latest"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

dns:
  replicaCount: 1

  image:
    repository: atnog-harbor.av.it.pt/gsma-open-gw-apis/ims-dns
    pullPolicy: Always # IfNotPresent
    tag: "latest"

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

dnsPatcher:
  image:
    repository: atnog-harbor.av.it.pt/gsma-open-gw-apis/ims-dns-patcher
    pullPolicy: Always # IfNotPresent
    tag: "latest"

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
