apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ccam-nef-bridge.fullname" . }}-config
  labels:
    {{- include "ccam-nef-bridge.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- toToml .Values.bridgeConfig | nindent 4 }}
