/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/one-time-password-sms/v1/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Code */
        post: operations["send_code_one_time_password_sms_v1_send_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/one-time-password-sms/v1/validate-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Code */
        post: operations["send_code_one_time_password_sms_v1_validate_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geofencing-subscriptions/v0/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subscription */
        get: operations["get_subscription_geofencing_subscriptions_v0_subscriptions_get"];
        put?: never;
        /** Post Subscriptions */
        post: operations["post_subscriptions_geofencing_subscriptions_v0_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geofencing-subscriptions/v0/subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subscriptions By Id */
        get: operations["get_subscriptions_by_id_geofencing_subscriptions_v0_subscriptions__subscriptionId__get"];
        put?: never;
        post?: never;
        /** Delete Subscriptions By Id */
        delete: operations["delete_subscriptions_by_id_geofencing_subscriptions_v0_subscriptions__subscriptionId__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geofencing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook */
        post: operations["webhook_geofencing_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Circle */
        "Circle-Input": {
            /**
             * Areatype
             * @default CIRCLE
             * @constant
             */
            areaType: "CIRCLE";
            center: components["schemas"]["Point"];
            /**
             * Radius
             * @description Expected accuracy for the subscription event of device location, in meters from `center`.
             *     Note: The area surface could be restricted locally depending on regulations. Implementations may enforce a larger minimum radius (e.g. 1000 meters).
             *
             */
            radius: number;
        };
        /** Circle */
        "Circle-Output": {
            /**
             * Areatype
             * @default CIRCLE
             * @constant
             */
            areaType: "CIRCLE";
            center: components["schemas"]["Point"];
            /**
             * Radius
             * @description Expected accuracy for the subscription event of device location, in meters from `center`.
             *     Note: The area surface could be restricted locally depending on regulations. Implementations may enforce a larger minimum radius (e.g. 1000 meters).
             *
             */
            radius: number;
        };
        /** Config */
        "Config-Input": {
            subscriptionDetail: components["schemas"]["SubscriptionDetail-Input"];
            /** Subscriptionexpiretime */
            subscriptionExpireTime?: string | null;
            /** Subscriptionmaxevents */
            subscriptionMaxEvents?: number | null;
            /** Initialevent */
            initialEvent?: boolean | null;
        };
        /** Config */
        "Config-Output": {
            subscriptionDetail: components["schemas"]["SubscriptionDetail-Output"];
            /** Subscriptionexpiretime */
            subscriptionExpireTime?: string | null;
            /** Subscriptionmaxevents */
            subscriptionMaxEvents?: number | null;
            /** Initialevent */
            initialEvent?: boolean | null;
        };
        /**
         * CredentialType
         * @enum {string}
         */
        CredentialType: "PLAIN" | "ACCESSTOKEN" | "REFRESHTOKEN";
        /** Device */
        "Device-Input": {
            /** Phonenumber */
            phoneNumber?: string | null;
            /** Networkaccessidentifier */
            networkAccessIdentifier?: string | null;
            ipv4Address?: components["schemas"]["DeviceIpv4Addr-Input"] | null;
            ipv6Address?: components["schemas"]["DeviceIpv6Address"] | null;
        };
        /** Device */
        "Device-Output": {
            /** Phonenumber */
            phoneNumber?: string | null;
            /** Networkaccessidentifier */
            networkAccessIdentifier?: string | null;
            ipv4Address?: components["schemas"]["DeviceIpv4Addr-Output"] | null;
            ipv6Address?: components["schemas"]["DeviceIpv6Address"] | null;
        };
        /**
         * DeviceIpv4Addr
         * @description The device should be identified by either the public (observed) IP address and port as seen by the application server, or the private (local) and any public (observed) IP addresses in use by the device (this information can be obtained by various means, for example from some DNS servers).
         *
         *     If the allocated and observed IP addresses are the same (i.e. NAT is not in use) then  the same address should be specified for both publicAddress and privateAddress.
         *
         *     If NAT64 is in use, the device should be identified by its publicAddress and publicPort, or separately by its allocated IPv6 address (field ipv6Address of the Device object)
         *
         *     In all cases, publicAddress must be specified, along with at least one of either privateAddress or publicPort, dependent upon which is known. In general, mobile devices cannot be identified by their public IPv4 address alone.
         *
         */
        "DeviceIpv4Addr-Input": components["schemas"]["DeviceIpv4Addr1"] | components["schemas"]["DeviceIpv4Addr2"];
        /**
         * DeviceIpv4Addr
         * @description The device should be identified by either the public (observed) IP address and port as seen by the application server, or the private (local) and any public (observed) IP addresses in use by the device (this information can be obtained by various means, for example from some DNS servers).
         *
         *     If the allocated and observed IP addresses are the same (i.e. NAT is not in use) then  the same address should be specified for both publicAddress and privateAddress.
         *
         *     If NAT64 is in use, the device should be identified by its publicAddress and publicPort, or separately by its allocated IPv6 address (field ipv6Address of the Device object)
         *
         *     In all cases, publicAddress must be specified, along with at least one of either privateAddress or publicPort, dependent upon which is known. In general, mobile devices cannot be identified by their public IPv4 address alone.
         *
         */
        "DeviceIpv4Addr-Output": components["schemas"]["DeviceIpv4Addr1"] | components["schemas"]["DeviceIpv4Addr2"];
        /** DeviceIpv4Addr1 */
        DeviceIpv4Addr1: {
            publicAddress: components["schemas"]["SingleIpv4Addr"];
            privateAddress: components["schemas"]["SingleIpv4Addr"];
            publicPort?: components["schemas"]["Port"] | null;
        };
        /** DeviceIpv4Addr2 */
        DeviceIpv4Addr2: {
            publicAddress: components["schemas"]["SingleIpv4Addr"];
            privateAddress?: components["schemas"]["SingleIpv4Addr"] | null;
            publicPort: components["schemas"]["Port"];
        };
        /**
         * DeviceIpv6Address
         * Format: ipv6
         * @description The device should be identified by the observed IPv6 address, or by any single IPv6 address from within the subnet allocated to the device (e.g. adding ::0 to the /64 prefix).
         *
         */
        DeviceIpv6Address: string;
        /** ErrorInfo */
        ErrorInfo: {
            /**
             * Status
             * @description HTTP response status code
             */
            status: number;
            /**
             * Code
             * @description Code given to this error
             */
            code: string;
            /**
             * Message
             * @description Detailed error description
             */
            message: string;
        };
        /** GeoPoint */
        GeoPoint: {
            shape: components["schemas"]["SupportedGADShapes"];
            point: components["schemas"]["GeographicalCoordinates"];
        };
        /** GeographicalCoordinates */
        GeographicalCoordinates: {
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Latitude
         * @description Latitude component of a location.
         */
        Latitude: number;
        /** LocationInfo */
        LocationInfo: {
            geographicArea?: components["schemas"]["GeoPoint"] | null;
        };
        /**
         * Longitude
         * @description Longitude component of location.
         */
        Longitude: number;
        /** MonitoringEventReport */
        MonitoringEventReport: {
            /** Externalid */
            externalId?: string | null;
            locationInfo?: components["schemas"]["LocationInfo"] | null;
            monitoringType: components["schemas"]["MonitoringType"];
        };
        /** MonitoringNotification */
        MonitoringNotification: {
            /**
             * Subscription
             * Format: uri
             */
            subscription: string;
            /** Monitoringeventreports */
            monitoringEventReports?: components["schemas"]["MonitoringEventReport"][] | null;
        };
        /**
         * MonitoringType
         * @enum {string}
         */
        MonitoringType: "LOCATION_REPORTING" | "LOSS_OF_CONNECTIVITY" | "UE_REACHABILITY";
        /** Point */
        Point: {
            latitude: components["schemas"]["Latitude"];
            longitude: components["schemas"]["Longitude"];
        };
        /**
         * Port
         * @description TCP or UDP port number.
         */
        Port: number;
        /**
         * Protocol
         * @enum {string}
         */
        Protocol: "HTTP" | "MQTT3" | "MQTT5" | "AMQP" | "NATS" | "KAFKA";
        /** SendCodeBody */
        SendCodeBody: {
            /**
             * Phonenumber
             * @description A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
             */
            phoneNumber: string;
            /**
             * Message
             * @description Message template used to compose the content of the SMS sent to the phone number. It must include the following label indicating where to include the short code `{{code}}`
             */
            message: string;
        };
        /** SendCodeResponse */
        SendCodeResponse: {
            /**
             * Authenticationid
             * @description unique id of the verification attempt the code belongs to.
             */
            authenticationId: string;
        };
        /**
         * SingleIpv4Addr
         * Format: ipv4
         * @description A single IPv4 address with no subnet mask.
         */
        SingleIpv4Addr: string;
        /** SinkCredential */
        SinkCredential: {
            /** @description The type of the credential. */
            credentialType: components["schemas"]["CredentialType"];
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "ACTIVATION_REQUESTED" | "ACTIVE" | "EXPIRED" | "INACTIVE" | "DELETED";
        /** Subscription */
        Subscription: {
            protocol: components["schemas"]["Protocol"];
            /**
             * Sink
             * @description The address to which events shall be delivered using the selected protocol.
             */
            sink: string;
            sinkCredential?: components["schemas"]["SinkCredential"] | null;
            /**
             * Types
             * @description Camara Event types eligible to be delivered by this subscription.
             *
             */
            types: components["schemas"]["SubscriptionEventType"][];
            config: components["schemas"]["Config-Output"];
            /**
             * Id
             * @description The unique identifier of the subscription in the scope of the subscription manager. When this information is contained within an event notification, this concept SHALL be referred as `subscriptionId` as per [Commonalities Event Notification Model](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#122-event-notification).
             */
            id: string;
            /**
             * Startsat
             * Format: date-time
             * @description Date when the event subscription will begin/began.
             */
            startsAt: string;
            /** Expiresat */
            expiresAt?: string | null;
            status?: components["schemas"]["Status"] | null;
        };
        /** SubscriptionDetail */
        "SubscriptionDetail-Input": {
            device: components["schemas"]["Device-Input"];
            area: components["schemas"]["Circle-Input"];
        };
        /** SubscriptionDetail */
        "SubscriptionDetail-Output": {
            device: components["schemas"]["Device-Output"];
            area: components["schemas"]["Circle-Output"];
        };
        /**
         * SubscriptionEventType
         * @enum {string}
         */
        SubscriptionEventType: "org.camaraproject.geofencing-subscriptions.v0.area-entered" | "org.camaraproject.geofencing-subscriptions.v0.area-left";
        /** SubscriptionRequest */
        SubscriptionRequest: {
            protocol: components["schemas"]["Protocol"];
            /**
             * Sink
             * @description The address to which events shall be delivered using the selected protocol.
             */
            sink: string;
            sinkCredential?: components["schemas"]["SinkCredential"] | null;
            /**
             * Types
             * @description Camara Event types which are eligible to be delivered by this subscription.
             *     Note: As of now we enforce to have only event type per subscription.
             *
             */
            types: components["schemas"]["SubscriptionEventType"][];
            config: components["schemas"]["Config-Input"];
        };
        /**
         * SupportedGADShapes
         * @enum {string}
         */
        SupportedGADShapes: "POINT";
        /** ValidateCodeBody */
        ValidateCodeBody: {
            /**
             * Authenticationid
             * @description unique id of the verification attempt the code belongs to.
             */
            authenticationId: string;
            /**
             * Code
             * @description temporal, short code to be validated
             */
            code: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Correlation id for the different services */
        "x-correlator": string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id for the different services */
        "x-correlator": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    send_code_one_time_password_sms_v1_send_code_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation id for the different services */
                "x-correlator"?: components["parameters"]["x-correlator"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendCodeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendCodeResponse"];
                };
            };
            /** @description Problem with the client request */
            400: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorInfo"];
                };
            };
        };
    };
    send_code_one_time_password_sms_v1_validate_code_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation id for the different services */
                "x-correlator"?: components["parameters"]["x-correlator"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateCodeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem with the client request. In addition to regular scenario of `INVALID_ARGUMENT`, another scenarios may exist:
             *       - Too many unsuccessful attempts (`{"code": "ONE_TIME_PASSWORD_SMS.VERIFICATION_FAILED","message": "The maximum number of attempts for this authenticationId was exceeded without providing a valid OTP"}`)
             *       - Expired authenticationId (`{"code": "ONE_TIME_PASSWORD_SMS.VERIFICATION_EXPIRED","message": "The authenticationId is no longer valid"}`)
             *       - OTP is not valid for the provided authenticationId (`{"code": "ONE_TIME_PASSWORD_SMS.INVALID_OTP","message": "The provided OTP is not valid for this authenticationId"}`)
             *              */
            400: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorInfo"];
                };
            };
        };
    };
    get_subscription_geofencing_subscriptions_v0_subscriptions_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation id for the different services */
                "x-correlator"?: components["parameters"]["x-correlator"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"][];
                };
            };
            /** @description Problem with the client request */
            400: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorInfo"];
                };
            };
        };
    };
    post_subscriptions_geofencing_subscriptions_v0_subscriptions_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation id for the different services */
                "x-correlator"?: components["parameters"]["x-correlator"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            /** @description Problem with the client request */
            400: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorInfo"];
                };
            };
        };
    };
    get_subscriptions_by_id_geofencing_subscriptions_v0_subscriptions__subscriptionId__get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation id for the different services */
                "x-correlator"?: components["parameters"]["x-correlator"];
            };
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            /** @description Problem with the client request */
            400: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorInfo"];
                };
            };
        };
    };
    delete_subscriptions_by_id_geofencing_subscriptions_v0_subscriptions__subscriptionId__delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation id for the different services */
                "x-correlator"?: components["parameters"]["x-correlator"];
            };
            path: {
                subscriptionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Problem with the client request */
            400: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorInfo"];
                };
            };
        };
    };
    webhook_geofencing_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation id for the different services */
                "x-correlator"?: components["parameters"]["x-correlator"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitoringNotification"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Problem with the client request */
            400: {
                headers: {
                    "x-correlator": components["headers"]["x-correlator"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorInfo"];
                };
            };
        };
    };
}
