apiVersion: v1
kind: Service
metadata:
  name: {{ include "ims.fullname" . }}-icscf
spec:
  type: ClusterIP
  clusterIP: "None"
  selector:
    {{- include "ims.icscfSelectorLabels" . | nindent 4 }}
  ports:
    - name: sip-udp
      protocol: UDP
      port: 6060
      targetPort: 6060
    - name: sip-tcp
      protocol: TCP
      port: 6060
      targetPort: 6060
    - name: diameter-udp
      protocol: UDP
      port: 3869
      targetPort: 3869
    - name: diameter-tcp
      protocol: TCP
      port: 3869
      targetPort: 3869
