apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "ims.fullname" . }}-icscf
spec:
  mariaDbRef:
    name: {{ include "ims.databaseInstanceName" . }}
  passwordSecretKeyRef:
    # kubectl create secret generic ims-icscf \
    #     --from-literal=password='icscf-password'
    name: {{ include "ims.fullname" . }}-icscf
    key: password
  maxUserConnections: 0
  cleanupPolicy: Delete
