apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "ims.fullname" . }}-pcscf
spec:
  mariaDbRef:
    name: {{ include "ims.databaseInstanceName" . }}
  name: "pcscf"
  cleanupPolicy: Delete
