apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "ims.fullname" . }}-pyhss
spec:
  mariaDbRef:
    name: {{ include "ims.databaseInstanceName" . }}
  passwordSecretKeyRef:
    # kubectl create secret generic ims-pyhss \
    #     --from-literal=password='pyhss-password'
    name: {{ include "ims.fullname" . }}-pyhss
    key: password
  cleanupPolicy: Delete
