apiVersion: v1
kind: Service
metadata:
  name: {{ include "ims.fullname" . }}-pyhss
spec:
  type: ClusterIP
  clusterIP: "None"
  selector:
    {{- include "ims.pyhssSelectorLabels" . | nindent 4 }}
  ports:
    - name: diameter-udp
      protocol: UDP
      port: 3868
      targetPort: 3868
    - name: diameter-tcp
      protocol: TCP
      port: 3868
      targetPort: 3868
    - name: api-http
      protocol: TCP
      port: 8080
      targetPort: 8080
