apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ims.fullname" . }}-pyhss
  labels:
    {{- include "ims.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pyhss.replicaCount }}
  selector:
    matchLabels:
      {{- include "ims.pyhssSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pyhss.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ims.labels" . | nindent 8 }}
        {{- include "ims.pyhssSelectorLabels" . | nindent 8 }}
        {{- with .Values.pyhss.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ims.serviceAccountName" . }}
      {{- with .Values.pyhss.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pyhss
          {{- with .Values.pyhss.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.pyhss.image.repository }}:{{ .Values.pyhss.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pyhss.image.pullPolicy }}
          ports:
            - name: diameter-udp
              containerPort: 3868
              protocol: UDP
            - name: diameter-tcp
              containerPort: 3868
              protocol: TCP
            - name: api-http
              containerPort: 8080
              protocol: TCP
          env:
            - name: IMS_DOMAIN
              value: {{ include "ims.mnoDomain" . }}
            - name: MCC
              value: "{{ .Values.mcc }}"
            - name: MNC
              value: "{{ .Values.mnc }}"
            - name: DATABASE_ADDR
              value: {{ include "ims.databaseInstanceName" . }}
            - name: DATABASE_USER
              value: {{ include "ims.fullname" . }}-pyhss
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ims.fullname" . }}-pyhss
                  key: password 
          {{- with .Values.pyhss.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: init-myservice
          image: "{{ .Values.dnsPatcher.image.repository }}:{{ .Values.dnsPatcher.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dnsPatcher.image.pullPolicy }}
          env:
            - name: RELEASE_NAME
              value: {{ include "ims.fullname" . }}
      # Disable the default DNS behaviour so that the nameserver can be patched
      # to use our DNS that includes the needed IMS and E164 zones.
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 127.0.0.20 # Dummy value that will be patched in the init container
        searches:
          - cluster.local
          - svc.cluster.local
          - {{ .Release.Namespace }}.svc.cluster.local
        options:
          - name: ndots
            value: "5"
          - name: edns0
      {{- with .Values.pyhss.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pyhss.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pyhss.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
