{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ims.fullname" . }}-read-svcs
  labels:
    {{- include "ims.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: 
      - {{ include "ims.fullname" . }}-dns
      - {{ include "ims.fullname" . }}-pcscf
    verbs: ["get"]
{{- end }}
