apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "ims.fullname" . }}-scscf
spec:
  mariaDbRef:
    name: {{ include "ims.databaseInstanceName" . }}
  passwordSecretKeyRef:
    # kubectl create secret generic ims-scscf \
    #     --from-literal=password='scscf-password'
    name: {{ include "ims.fullname" . }}-scscf
    key: password
  maxUserConnections: 0
  cleanupPolicy: Delete
