apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "ims.fullname" . }}-scscf
spec:
  mariaDbRef:
    name: {{ include "ims.databaseInstanceName" . }}
  name: "scscf"
  cleanupPolicy: Delete
