apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: {{ include "ims.fullname" . }}-smsc
spec:
  mariaDbRef:
    name: {{ include "ims.databaseInstanceName" . }}
  passwordSecretKeyRef:
    # kubectl create secret generic ims-smsc \
    #     --from-literal=password='smsc-password'
    name: {{ include "ims.fullname" . }}-smsc
    key: password
  maxUserConnections: 0
  cleanupPolicy: Delete
