apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ims.fullname" . }}-smsc
  labels:
    {{- include "ims.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.smsc.replicaCount }}
  selector:
    matchLabels:
      {{- include "ims.smscSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.smsc.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ims.labels" . | nindent 8 }}
        {{- include "ims.smscSelectorLabels" . | nindent 8 }}
        {{- with .Values.smsc.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ims.serviceAccountName" . }}
      {{- with .Values.smsc.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: smsc
          {{- with .Values.smsc.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.smsc.image.repository }}:{{ .Values.smsc.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.smsc.image.pullPolicy }}
          ports:
            - name: sip-udp
              containerPort: 7090
              protocol: UDP
            - name: sip-tcp
              containerPort: 7090
              protocol: TCP
          env:
            - name: IMS_DOMAIN
              value: {{ include "ims.mnoDomain" . }}
            - name: ADVERTISE_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_ADDR
              value: {{ include "ims.databaseInstanceName" . }}
            - name: DATABASE_USER
              value: {{ include "ims.fullname" . }}-smsc
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ims.fullname" . }}-smsc
                  key: password 
          {{- with .Values.smsc.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      initContainers:
        - name: init-myservice
          image: "{{ .Values.dnsPatcher.image.repository }}:{{ .Values.dnsPatcher.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dnsPatcher.image.pullPolicy }}
          env:
            - name: RELEASE_NAME
              value: {{ include "ims.fullname" . }}
      # Disable the default DNS behaviour so that the nameserver can be patched
      # to use our DNS that includes the needed IMS and E164 zones.
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 127.0.0.20 # Dummy value that will be patched in the init container
        searches:
          - cluster.local
          - svc.cluster.local
          - {{ .Release.Namespace }}.svc.cluster.local
        options:
          - name: ndots
            value: "5"
          - name: edns0
      {{- with .Values.smsc.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.smsc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.smsc.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
