/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ManagementIndexImport } from './routes/management/index'
import { Route as InfotainmentIndexImport } from './routes/infotainment/index'
import { Route as InfotainmentVideoIdIndexImport } from './routes/infotainment/$videoId/index'
import { Route as authValidateIndexImport } from './routes/(auth)/validate/index'
import { Route as authRegisterIndexImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'
import { Route as ManagementTruckTruckIdImport } from './routes/management/truck/$truckId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ManagementIndexRoute = ManagementIndexImport.update({
  id: '/management/',
  path: '/management/',
  getParentRoute: () => rootRoute,
} as any)

const InfotainmentIndexRoute = InfotainmentIndexImport.update({
  id: '/infotainment/',
  path: '/infotainment/',
  getParentRoute: () => rootRoute,
} as any)

const InfotainmentVideoIdIndexRoute = InfotainmentVideoIdIndexImport.update({
  id: '/infotainment/$videoId/',
  path: '/infotainment/$videoId/',
  getParentRoute: () => rootRoute,
} as any)

const authValidateIndexRoute = authValidateIndexImport.update({
  id: '/(auth)/validate/',
  path: '/validate/',
  getParentRoute: () => rootRoute,
} as any)

const authRegisterIndexRoute = authRegisterIndexImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const ManagementTruckTruckIdRoute = ManagementTruckTruckIdImport.update({
  id: '/management/truck/$truckId',
  path: '/management/truck/$truckId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/infotainment/': {
      id: '/infotainment/'
      path: '/infotainment'
      fullPath: '/infotainment'
      preLoaderRoute: typeof InfotainmentIndexImport
      parentRoute: typeof rootRoute
    }
    '/management/': {
      id: '/management/'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementIndexImport
      parentRoute: typeof rootRoute
    }
    '/management/truck/$truckId': {
      id: '/management/truck/$truckId'
      path: '/management/truck/$truckId'
      fullPath: '/management/truck/$truckId'
      preLoaderRoute: typeof ManagementTruckTruckIdImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/validate/': {
      id: '/(auth)/validate/'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof authValidateIndexImport
      parentRoute: typeof rootRoute
    }
    '/infotainment/$videoId/': {
      id: '/infotainment/$videoId/'
      path: '/infotainment/$videoId'
      fullPath: '/infotainment/$videoId'
      preLoaderRoute: typeof InfotainmentVideoIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/infotainment': typeof InfotainmentIndexRoute
  '/management': typeof ManagementIndexRoute
  '/management/truck/$truckId': typeof ManagementTruckTruckIdRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/validate': typeof authValidateIndexRoute
  '/infotainment/$videoId': typeof InfotainmentVideoIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/infotainment': typeof InfotainmentIndexRoute
  '/management': typeof ManagementIndexRoute
  '/management/truck/$truckId': typeof ManagementTruckTruckIdRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/validate': typeof authValidateIndexRoute
  '/infotainment/$videoId': typeof InfotainmentVideoIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/infotainment/': typeof InfotainmentIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/management/truck/$truckId': typeof ManagementTruckTruckIdRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(auth)/validate/': typeof authValidateIndexRoute
  '/infotainment/$videoId/': typeof InfotainmentVideoIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/infotainment'
    | '/management'
    | '/management/truck/$truckId'
    | '/login'
    | '/register'
    | '/validate'
    | '/infotainment/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/infotainment'
    | '/management'
    | '/management/truck/$truckId'
    | '/login'
    | '/register'
    | '/validate'
    | '/infotainment/$videoId'
  id:
    | '__root__'
    | '/'
    | '/infotainment/'
    | '/management/'
    | '/management/truck/$truckId'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(auth)/validate/'
    | '/infotainment/$videoId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfotainmentIndexRoute: typeof InfotainmentIndexRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
  ManagementTruckTruckIdRoute: typeof ManagementTruckTruckIdRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  authValidateIndexRoute: typeof authValidateIndexRoute
  InfotainmentVideoIdIndexRoute: typeof InfotainmentVideoIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfotainmentIndexRoute: InfotainmentIndexRoute,
  ManagementIndexRoute: ManagementIndexRoute,
  ManagementTruckTruckIdRoute: ManagementTruckTruckIdRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  authValidateIndexRoute: authValidateIndexRoute,
  InfotainmentVideoIdIndexRoute: InfotainmentVideoIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/infotainment/",
        "/management/",
        "/management/truck/$truckId",
        "/(auth)/login/",
        "/(auth)/register/",
        "/(auth)/validate/",
        "/infotainment/$videoId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/infotainment/": {
      "filePath": "infotainment/index.tsx"
    },
    "/management/": {
      "filePath": "management/index.tsx"
    },
    "/management/truck/$truckId": {
      "filePath": "management/truck/$truckId.tsx"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/(auth)/register/": {
      "filePath": "(auth)/register/index.tsx"
    },
    "/(auth)/validate/": {
      "filePath": "(auth)/validate/index.tsx"
    },
    "/infotainment/$videoId/": {
      "filePath": "infotainment/$videoId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
