apiVersion: v1
kind: Service
metadata:
  name: {{ include "gsma-open-gateway.fullname" . }}
  labels:
    {{- include "gsma-open-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "gsma-open-gateway.selectorLabels" . | nindent 4 }}
