/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ManagementImport } from './routes/management'
import { Route as IndexImport } from './routes/index'
import { Route as ManagementIndexImport } from './routes/management/index'
import { Route as InfotainmentIndexImport } from './routes/infotainment/index'
import { Route as InfotainmentVideoIdIndexImport } from './routes/infotainment/$videoId/index'
import { Route as ManagementTruckTruckIdIndexImport } from './routes/management/truck/$truckId/index'
import { Route as InfotainmentauthValidateIndexImport } from './routes/infotainment/(auth)/validate/index'
import { Route as InfotainmentauthRegisterIndexImport } from './routes/infotainment/(auth)/register/index'
import { Route as InfotainmentauthLoginIndexImport } from './routes/infotainment/(auth)/login/index'

// Create/Update Routes

const ManagementRoute = ManagementImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ManagementIndexRoute = ManagementIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagementRoute,
} as any)

const InfotainmentIndexRoute = InfotainmentIndexImport.update({
  id: '/infotainment/',
  path: '/infotainment/',
  getParentRoute: () => rootRoute,
} as any)

const InfotainmentVideoIdIndexRoute = InfotainmentVideoIdIndexImport.update({
  id: '/infotainment/$videoId/',
  path: '/infotainment/$videoId/',
  getParentRoute: () => rootRoute,
} as any)

const ManagementTruckTruckIdIndexRoute =
  ManagementTruckTruckIdIndexImport.update({
    id: '/truck/$truckId/',
    path: '/truck/$truckId/',
    getParentRoute: () => ManagementRoute,
  } as any)

const InfotainmentauthValidateIndexRoute =
  InfotainmentauthValidateIndexImport.update({
    id: '/infotainment/(auth)/validate/',
    path: '/infotainment/validate/',
    getParentRoute: () => rootRoute,
  } as any)

const InfotainmentauthRegisterIndexRoute =
  InfotainmentauthRegisterIndexImport.update({
    id: '/infotainment/(auth)/register/',
    path: '/infotainment/register/',
    getParentRoute: () => rootRoute,
  } as any)

const InfotainmentauthLoginIndexRoute = InfotainmentauthLoginIndexImport.update(
  {
    id: '/infotainment/(auth)/login/',
    path: '/infotainment/login/',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementImport
      parentRoute: typeof rootRoute
    }
    '/infotainment/': {
      id: '/infotainment/'
      path: '/infotainment'
      fullPath: '/infotainment'
      preLoaderRoute: typeof InfotainmentIndexImport
      parentRoute: typeof rootRoute
    }
    '/management/': {
      id: '/management/'
      path: '/'
      fullPath: '/management/'
      preLoaderRoute: typeof ManagementIndexImport
      parentRoute: typeof ManagementImport
    }
    '/infotainment/$videoId/': {
      id: '/infotainment/$videoId/'
      path: '/infotainment/$videoId'
      fullPath: '/infotainment/$videoId'
      preLoaderRoute: typeof InfotainmentVideoIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/infotainment/(auth)/login/': {
      id: '/infotainment/(auth)/login/'
      path: '/infotainment/login'
      fullPath: '/infotainment/login'
      preLoaderRoute: typeof InfotainmentauthLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/infotainment/(auth)/register/': {
      id: '/infotainment/(auth)/register/'
      path: '/infotainment/register'
      fullPath: '/infotainment/register'
      preLoaderRoute: typeof InfotainmentauthRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/infotainment/(auth)/validate/': {
      id: '/infotainment/(auth)/validate/'
      path: '/infotainment/validate'
      fullPath: '/infotainment/validate'
      preLoaderRoute: typeof InfotainmentauthValidateIndexImport
      parentRoute: typeof rootRoute
    }
    '/management/truck/$truckId/': {
      id: '/management/truck/$truckId/'
      path: '/truck/$truckId'
      fullPath: '/management/truck/$truckId'
      preLoaderRoute: typeof ManagementTruckTruckIdIndexImport
      parentRoute: typeof ManagementImport
    }
  }
}

// Create and export the route tree

interface ManagementRouteChildren {
  ManagementIndexRoute: typeof ManagementIndexRoute
  ManagementTruckTruckIdIndexRoute: typeof ManagementTruckTruckIdIndexRoute
}

const ManagementRouteChildren: ManagementRouteChildren = {
  ManagementIndexRoute: ManagementIndexRoute,
  ManagementTruckTruckIdIndexRoute: ManagementTruckTruckIdIndexRoute,
}

const ManagementRouteWithChildren = ManagementRoute._addFileChildren(
  ManagementRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/management': typeof ManagementRouteWithChildren
  '/infotainment': typeof InfotainmentIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/infotainment/$videoId': typeof InfotainmentVideoIdIndexRoute
  '/infotainment/login': typeof InfotainmentauthLoginIndexRoute
  '/infotainment/register': typeof InfotainmentauthRegisterIndexRoute
  '/infotainment/validate': typeof InfotainmentauthValidateIndexRoute
  '/management/truck/$truckId': typeof ManagementTruckTruckIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/infotainment': typeof InfotainmentIndexRoute
  '/management': typeof ManagementIndexRoute
  '/infotainment/$videoId': typeof InfotainmentVideoIdIndexRoute
  '/infotainment/login': typeof InfotainmentauthLoginIndexRoute
  '/infotainment/register': typeof InfotainmentauthRegisterIndexRoute
  '/infotainment/validate': typeof InfotainmentauthValidateIndexRoute
  '/management/truck/$truckId': typeof ManagementTruckTruckIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/management': typeof ManagementRouteWithChildren
  '/infotainment/': typeof InfotainmentIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/infotainment/$videoId/': typeof InfotainmentVideoIdIndexRoute
  '/infotainment/(auth)/login/': typeof InfotainmentauthLoginIndexRoute
  '/infotainment/(auth)/register/': typeof InfotainmentauthRegisterIndexRoute
  '/infotainment/(auth)/validate/': typeof InfotainmentauthValidateIndexRoute
  '/management/truck/$truckId/': typeof ManagementTruckTruckIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/management'
    | '/infotainment'
    | '/management/'
    | '/infotainment/$videoId'
    | '/infotainment/login'
    | '/infotainment/register'
    | '/infotainment/validate'
    | '/management/truck/$truckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/infotainment'
    | '/management'
    | '/infotainment/$videoId'
    | '/infotainment/login'
    | '/infotainment/register'
    | '/infotainment/validate'
    | '/management/truck/$truckId'
  id:
    | '__root__'
    | '/'
    | '/management'
    | '/infotainment/'
    | '/management/'
    | '/infotainment/$videoId/'
    | '/infotainment/(auth)/login/'
    | '/infotainment/(auth)/register/'
    | '/infotainment/(auth)/validate/'
    | '/management/truck/$truckId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagementRoute: typeof ManagementRouteWithChildren
  InfotainmentIndexRoute: typeof InfotainmentIndexRoute
  InfotainmentVideoIdIndexRoute: typeof InfotainmentVideoIdIndexRoute
  InfotainmentauthLoginIndexRoute: typeof InfotainmentauthLoginIndexRoute
  InfotainmentauthRegisterIndexRoute: typeof InfotainmentauthRegisterIndexRoute
  InfotainmentauthValidateIndexRoute: typeof InfotainmentauthValidateIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagementRoute: ManagementRouteWithChildren,
  InfotainmentIndexRoute: InfotainmentIndexRoute,
  InfotainmentVideoIdIndexRoute: InfotainmentVideoIdIndexRoute,
  InfotainmentauthLoginIndexRoute: InfotainmentauthLoginIndexRoute,
  InfotainmentauthRegisterIndexRoute: InfotainmentauthRegisterIndexRoute,
  InfotainmentauthValidateIndexRoute: InfotainmentauthValidateIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/management",
        "/infotainment/",
        "/infotainment/$videoId/",
        "/infotainment/(auth)/login/",
        "/infotainment/(auth)/register/",
        "/infotainment/(auth)/validate/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/management": {
      "filePath": "management.tsx",
      "children": [
        "/management/",
        "/management/truck/$truckId/"
      ]
    },
    "/infotainment/": {
      "filePath": "infotainment/index.tsx"
    },
    "/management/": {
      "filePath": "management/index.tsx",
      "parent": "/management"
    },
    "/infotainment/$videoId/": {
      "filePath": "infotainment/$videoId/index.tsx"
    },
    "/infotainment/(auth)/login/": {
      "filePath": "infotainment/(auth)/login/index.tsx"
    },
    "/infotainment/(auth)/register/": {
      "filePath": "infotainment/(auth)/register/index.tsx"
    },
    "/infotainment/(auth)/validate/": {
      "filePath": "infotainment/(auth)/validate/index.tsx"
    },
    "/management/truck/$truckId/": {
      "filePath": "management/truck/$truckId/index.tsx",
      "parent": "/management"
    }
  }
}
ROUTE_MANIFEST_END */
