name: Build Gateway

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-gateway.yml"
      - "gateway/**"

jobs:
  backend:
    name: Build gateway container
    runs-on: ubuntu-latest
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: atnog-harbor.av.it.pt
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:gateway"
          tags: atnog-harbor.av.it.pt/gsma-open-gw-apis/gateway
