name: Lint CCAM NEF Bridge

on:
  push:
    branches:
      - main
    paths:
      - "ccam-nef-bridge/**"
      - ".github/workflows/lint-ccam-bridge.yml"
  pull_request:
    paths:
      - "ccam-nef-bridge/**"
      - ".github/workflows/lint-ccam-bridge.yml"

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ccam-nef-bridge
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check formatting
        run: uv run ruff format --check

      - name: Lint
        run: uv run ruff check
        if: always()

      - name: Type Checking
        run: uv run mypy .
        if: always()
